/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haocai_socketclient_SocketUtil */

#ifndef _Included_com_haocai_socketclient_SocketUtil
#define _Included_com_haocai_socketclient_SocketUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haocai_socketclient_SocketUtil
 * Method:    startClient
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_haocai_socketclient_SocketUtil_startClient
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
